version: '3.7'

services:
  web:
    image: jenga_web:latest
    build:
        context: ./app
        dockerfile: Dockerfile.prod
    command: gunicorn jenga.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/mediafiles
    expose:
        - 8000
    env_file:
        - ./.env.prod
    depends_on:
        - db
    deploy: 
        replicas: 2
        update_config:
            parallelism: 1
            delay: 10s
        restart_policy:
            condition: on-failure
  db:
    image: postgres:12.0-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env.prod.db
    deploy: 
        replicas: 2
        update_config:
            parallelism: 1
            delay: 10s
        restart_policy:
            condition: on-failure
  nginx:
    image: jenga_nginx:latest
    build: ./nginx
    volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/mediafiles
    ports:
        - 80:80
    depends_on:
        - web
    deploy:
        mode: global

volumes:
  postgres_data:
  static_volume:
  media_volume: