# Generated by Django 2.2.6 on 2020-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190829_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ManyToManyField(related_name='category', to='contacts.Contact_Group'),
        ),
    ]
